### ISSUE TITLE
[TN-271] Account for when server admin removes humanID Verified role entirely

### ISSUE THREAD

**Issue by ccrawford4** [human-internet/discord-bot#119]
Task: If a admin or member tries to use one of the bot's commands and the humanID Verified role has been removed, respond with this message: 

"The 'humanID Verified' role has been removed. If you are the server admin please recreate the 'humanID Verified' role to continue using the humanID Verification bot"

**Comment by ccrawford4** [comment]
@bastian-purrer Proposed error message ^

**Comment by bastian-purrer** [comment]
@ccrawford4 why is it called "Verification Role" once and "Verified Role" after? also as admin, i wouldn't think this instructions are very clear. what if we phrase it as:
> The 'humanID Verified' role has been removed. If you are the server admin please recreate the 'humanID Verified' role to continue using the humanID Verification bot"

**Comment by tech-lead-humanID** [comment]
> [@ccrawford4](https://github.com/ccrawford4) why is it called "Verification Role" once and "Verified Role" after? also as admin, i wouldn't think this instructions are very clear. what if we phrase it as:
> 
> > The 'humanID Verified' role has been removed. If you are the server admin please recreate the 'humanID Verified' role to continue using the humanID Verification bot"

Done

**Comment by tech-lead-humanID** [comment]
Currently account for the case in this way:
During the verification process, if the bot detecting that the "humanID-Verified" role has been removed, would try to add it back again. 
If can't, just complaining the permission stuff as always.
