### ISSUE TITLE
Admin Rights Bug - Discordbot won't install/setup

### ISSUE THREAD

**Issue by DeBelg** [human-internet/discord-bot#151]
<img width="1225" alt="Screenshot 2024-08-04 at 13 53 54" src="https://github.com/user-attachments/assets/8f42f371-ce06-4531-9923-1329d6a6e1ba">

<img width="1291" alt="Screenshot 2024-08-04 at 13 55 21" src="https://github.com/user-attachments/assets/c8fcf2e2-dd09-4d54-8b81-b7cffe241222">

As per images, after a fresh install the bot will not allow me to set it up. Nor allow me to register te get-verified channel.

**Comment by bastian-purrer** [comment]
@Lunasocute please update status
