### ISSUE TITLE
[TN-296] Assign existing users the "humanID-Verified" role when the discord bot just gets added in

### ISSUE THREAD

**Issue by Lunasocute** [human-internet/discord-bot#155]
Grant the "humanID-Verified" role to every existing user once the bot has been added to the server.

@bastian-purrer Anything else to add?

**Comment by suganeswar03** [comment]
so after the bot gets added, the verified role will be given to all users in the server, After that there should be an entry in the database as well?

**Comment by bastian-purrer** [comment]
@suganeswar03 
> After that there should be an entry in the database as well?
I don't understand what you mean by this part
