### ISSUE TITLE
TN146 - Give a more detailed description about role setup

### ISSUE THREAD

**Issue by tech-lead-humanID** [human-internet/discord-bot#40]

**Comment by vxcent** [comment]
This was mostly done on the GitBook discord bot setup instructions. When a
server admin sets up discord bot, they need to make sure the humanID
Discord Bot has a higher priority than their humanId_Verified role. That
way, the bot can actually assign the verified role onto other users.

**Comment by ccrawford4** [comment]
@vxcent ah okay, it looks like you did this already, thank you!
