### ISSUE TITLE
TN146 - Better-looking URL preview for verification

### ISSUE THREAD

**Issue by RicHH2** [human-internet/discord-bot#57]
https://docs.google.com/document/d/1YPLngeKRKQuLK3eSiSn4h5vMeh1wpDKmAYyzD8ru18g/edit

[Major] Didn’t we have a nicer preview here in some point and a humanID branded URL? Where did that go

**Comment by ccrawford4** [comment]
@bastian-purrer you moved this to Done & Live on Production, can I close this issue?

**Comment by bastian-purrer** [comment]
@ccrawford4 if i moved it to Done, i consider it closed
