### ISSUE TITLE
[TN-245] Implement a more User-Friendly Error Message for Users Trying to Verify for a Server They Already Have Access To

### ISSUE THREAD

**Issue by ccrawford4** [human-internet/discord-bot#93]
Right now if you try to use the '/verify' command for a server you already have access to it gives a somewhat unpleasing or unhelpful error message:

![Image](https://github.com/human-internet/discord-bot/assets/123438979/04de3dcf-1ef9-426b-b2aa-5233762ea1b4)

Creating a more user-friendly interface to handle these errors would look more professional. Then when you press the please try again button:

![Image](https://github.com/human-internet/discord-bot/assets/123438979/085582c5-d89f-4a30-bfd6-3a0022555f67)

Sub Tasks:
1.  Run the Discord Bot locally
2. Change the error message to "You already have verified yourself on this server" and redirect the user back to the Discord Server
3. When finished, send a screen-recording of the behavior to the #tech channel and @ bastian and calum for approval
4. Once approved, create a PR of your feature branch to merge into main.

**Comment by ccrawford4** [comment]
@bastian-purrer First ticket for Kyle, let me know you thoughts. Also if we have a different design we want instead of a plain error message I am open changing this.

**Comment by bastian-purrer** [comment]
@ccrawford4 makes sense. minor comment: the user is technically not trying to "get access", but to "verify", so the wording might be slightly misleading?
