### ISSUE TITLE
[TN-246] Change the Discord-Bot Error Message For Servers w/o Credentials

### ISSUE THREAD

**Issue by ccrawford4** [human-internet/discord-bot#95]
Please change the discord-bot error message from "This server does not have associated credentials. Please ask an admin to add this server from the humanID developer console." to "Your server is not yet registered with humanID. Please ask an admin to go to https://developers.human-id.org/ to register. 
For a more detailed step-by-step walk-through, go to https://docs.human-id.org/discord-bot-integration-guide.

Here is what it currently looks like when a user tries to use the /verify command without having the admin register the server in the humanID Developer Console: 

![Image](https://github.com/human-internet/discord-bot/assets/123438979/8f03f2db-651f-4ce2-a120-64f0d51ec792)

Steps:
1. Clone the discord-bot repo and then create a new branch. ```git checkout -b <new_branch_name>``` Branch naming conventions typically follows this: feature/[your initals]/[feature name] for example: ```git checkout -b feature/cc/error-message-change```
2. Run the Discord-Bot locally and test in your own test server (Just create a new discord-server) and add the bot to the server
3. Change the error message
4. Attempt to use the /verify command in your #get_verified channel the message returned should match what you changed it to.
5. Send a screen-recording or screenshot to the #tech channel and @ calum and bastian.
6. Once approved, create a PR to merge your branch into main and request review from Calum and Kofi
7. Once approved, your

**Comment by ccrawford4** [comment]
@bastian-purrer new ticket, let me know thoughts/changes before I put it in the Ready For Develop Category

**Comment by bastian-purrer** [comment]
@ccrawford4 looks good
